### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by admeister** [SitePen/remap-istanbul#102]
When using Typescript, and files have bene transpiled, if the original file only contained an Interface, the 'rawSourceMap.sources' is blank. When performing a remap you get the error:

```
TypeError: Path must be a string. Received undefined
/node_modules/remap-istanbul/lib/remap.js:288:14
```

A check needs to be performed first to see if sources does in fact containing any sources.

**Comment by admeister** [comment]
I see this has already been fixed. Any idea when you'll have a new version of remap-istanbul with this fix in?

**Comment by dylans** [comment]
@admeister soon... this week or next is the plan.
