### ISSUE TITLE
If sourceRoot is set in map file html report fails

### ISSUE THREAD

**Issue by stevehipwell** [SitePen/remap-istanbul#11]
If the `sourceRoot` value is set to anything except an empty string in the map file the html report can't be created. The map file works fine in Chrome and I'd like to go back to the default behavior as it make debugging easier.

**Comment by kitsonk** [comment]
When you say "can't be created" what specifically occurs?

**Comment by stevehipwell** [comment]
@kitsonk I get a stack trace from gulp saying that the file doesn't exists. The file path has an extra `/source/` folder in it that is coming from the `sourceRoot` value in the map file. The html report loads up the first view correctly but cannot show the individual files. Having a valid `sourceRoot` in the map file is pretty important to us as we are a large project and this makes debugging in chrome significantly easier.

The `sourceRoot` attribute is dictating where to reconstruct the embedded source code and has nothing to do with where the actual source code files are located. I see two solutions to this.

1. Use the embedded source code.
2. Ignore `sourceRoot` completely and use the separate typescript files located next to the map files.

**Comment by ariporad** [comment]
@kitsonk: I'm having this too. My repo is emiw/redstone-dispatcher#istanbul-source-maps, if you'd like to take a look.

**Comment by kitsonk** [comment]
Yes, I think there is something too this.

**Comment by ariporad** [comment]
Hey, @kitsonk, what's the status on this? I'd really love to be able to use remap-istanbul.

**Comment by kitsonk** [comment]
We should get time this week.  Hopefully...

**Comment by ghpabs** [comment]
@ariporad has your repo been removed or did the Url change? I'm getting a 404 error in the link above.

**Comment by ariporad** [comment]
@ghpabs: The branch changed. (I actually just ended up using istanbul@1, which has source-maps built in). I can create a demo for you if you want.

**Comment by ghpabs** [comment]
@ariporad Yes that would be great, thanks!

**Comment by kitsonk** [comment]
Ok, I finally got some time to see the issue...  The problem is that inline sources have become a "thing", which `remap-istanbul` wasn't configured to handle.  I see the problem now and am working on a fix.

**Comment by kitsonk** [comment]
Hmmm... I am going to have to think about this a bit...  It isn't actually remapIstanbul that is having the problem.  It goes through the remapping process perfectly fine.  It is actually Istanbul, when generating the report, can't locate the source files, because they happen to be only available in the source-map.  In order to get this to work, I suspect I will have to create a virtual file system for the HTML reporter to read from.

Of course, a workaround is to have the sources available in a accessible path for the HTML reporter.

**Comment by ariporad** [comment]
@kitsonk: it's probobly not worth your time, as istanbul 1 (currently in alpha) has built in source map support.

**Comment by kitsonk** [comment]
@ariporad yes, but I know that the timeline for Istanbul 1 is always a bit variable and others are encountering the issue.  I don't know how quickly some folks will be able to move to Istanbul 1, especially when some are dependent upon their test harness to update.

**Comment by ghpabs** [comment]
@kitsonk would you be able to point me to an example where Istanbul v1 alpha is implemented with Karma using source map?

**Comment by kitsonk** [comment]
@ghpabs I haven't been using Istanbul v1 alpha.  Best to check out the work at [IstanbulJS](https://github.com/istanbuljs).

**Comment by ghpabs** [comment]
Oh god, sorry I meant to mention @ariporad instead as he seemed familiar with v1. I'll leave now. Thanks for sharing `remap-istanbul` though. It's been very helpful.
