### ISSUE TITLE
No coverage generated for Intern.

### ISSUE THREAD

**Issue by iyegoroff** [SitePen/remap-istanbul#113]
JsonCoverage reporter doesn't produce any coverage with intern-runner & intern-client when using remap-istanbul 0.8.1 or 0.8.2.

**Comment by dylans** [comment]
So the issue we have is 0.8.0 fixed a number of things, and regressed for a number of other users. 0.8.1 and 0.8.2 attempted to fix that and have now regressed things for people where 0.8.0 was working fine. Apologies, we're working to fix asap.

**Comment by iyegoroff** [comment]
No problem, thanks!

**Comment by jdonaghue** [comment]
@iyegoroff could you take a look at PR #114 and see if that fixes this issue. It should. I was able to generate coverage locally with this fix.

**Comment by iyegoroff** [comment]
@jdonaghue, yes - version from 0.8.x-issues branch fixed the problem for me.

**Comment by jdonaghue** [comment]
@iyegoroff thanks for confirming! `0.8.3` has been released and includes this fix.
