### ISSUE TITLE
verbose output option for cli?

### ISSUE THREAD

**Issue by kwonoj** [SitePen/remap-istanbul#13]
While running remap-istanbul on CI, could observe intermittent failures like below

```
remap-istanbul -i coverage/coverage.json -o coverage/coverage-remapped.json && remap-istanbul -i coverage/coverage.json -o coverage/coverage-remapped.lcov -t lcovonly && remap-istanbul -i coverage/coverage.json -o coverage/coverage-remapped -t html
The command "npm test && npm run cover" exited with 0.
cache.2
store build cache
1.71snothing changed, not updating cache
after_script
0.31s$ cat ./coverage/coverage-remapped.lcov  | ./node_modules/coveralls/bin/coveralls.js
cat: ./coverage/coverage-remapped.lcov: No such file or directory
[error] "2015-10-30T17:17:58.950Z"  'error from lcovParse: ' 'Failed to parse string'
[error] "2015-10-30T17:17:58.952Z"  'input: ' ''
[error] "2015-10-30T17:17:58.953Z"  'error from convertLcovToCoveralls'
```

remapped output is not produced. Trying to triage issue but there isn't any messages from remap-istanbul, hard to find where to start. Is there any way to check behaviors?

**Comment by kitsonk** [comment]
Good idea...

**Comment by kitsonk** [comment]
I have looked at this and generally whenever there is an issue in the code, there is either something written to console.warn or console.error.  I suspect though there might be an issue with handling the stdin for some reason, essentially what is being piped isn't valid JSON and the cli will silently fail, so I will fix that.

**Comment by kwonoj** [comment]
Appreciate for help! :+1:
