### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by joashmusyoka** [SitePen/remap-istanbul#136]
I get the above error when running the remap command as follows

> remap-istanbul -i coverage/coverage.json -o coverage -t html

The problem seems to come from:

node_modules\remap-istanbul\bin\remap-istanbul.js:21
                let buffer = '';

If I use strict in the above file, then all is good.

I am tsfying using es6 config.

**Comment by dylans** [comment]
@joashmusyoka which version of Node.js are you using? It sounds to me like we didn't test with older versions of Node.js here (e.g. prior to version 4?).

**Comment by joashmusyoka** [comment]
Am using node version 4.1.2

**Comment by dylans** [comment]
ok, thanks, i guess this only changed in Node 6 then.

If you want to do a PR to add a use strict pragma, I'll review and land it, otherwise I'll do the same sometime this week. Thanks again.

**Comment by joashmusyoka** [comment]
Let me do a PR for it tomorrow. Thanks a lot.
