### ISSUE TITLE
support ignore comments

### ISSUE THREAD

**Issue by synectic** [SitePen/remap-istanbul#14]
The instanbul library has a system to ignore certain parts of the code ([see](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md)). This doesn't work correctly after the remap.

I inspected the coverage.json files and a location entry has in addition to `start` and `end` also a `skip` property.

original coverage.json
```
"locations":[{"start":{"line":1,"column":11},"end":{"line":1,"column":19}},{"start":{"line":31,"column":1},"end":{"line":null,"column":-1}}]}
```

remapped coverage.json
```
"locations":[{"start":{"line":32,"column":18},"end":{"line":32,"column":30}},{"start":{"line":32,"column":74},"end":{"line":32,"column":91},"skip":true}]}
```

I suspect the only thing missing for this to work, is to transfer the skip property.

**Comment by kitsonk** [comment]
PR #12 address this... I will hopefully land it (or something similar) this week.
