### ISSUE TITLE
remap-istanbul throws error for non-compiled source

### ISSUE THREAD

**Issue by Balrog30** [SitePen/remap-istanbul#15]
Our project includes mostly typescript compiled to javascript, with sourcemaps generated by TypeScript. When I use remap-istanbul for a pure-typescript project it works just fine. However, when running against coverage data that also includes a plain javascript file, and hence no source map for that file, I get `[Error: Could not find source map for: "/path/to/file.js" ]`. The coverage is generated with `istanbul cover` command for a node project. The plain javascript module is imported with `require()`.

**Comment by kitsonk** [comment]
I don't think this is something we considered.  Ideally `remap-instanbul` should potentially warn on these sort of issues instead of throwing.  I think I know what we need to do to fix this.

**Comment by Balrog30** [comment]
Given that no source map present is normal behaviour for my case, I don't think a warning is necessary. Perhaps a verbose flag would be desirable? Maybe that's over-engineering such a simple utility, though.

**Comment by Balrog30** [comment]
I haven't had a chance to try this, but thank you for addressing my issue.
