### ISSUE TITLE
TypeError: sourceMap.originalPositionFor is not a function (pulling wrong source-map version?)

### ISSUE THREAD

**Issue by mtraynham** [SitePen/remap-istanbul#162]
I'm getting the following error:
```
TypeError: sourceMap.originalPositionFor is not a function
[INFO]     at getMapping (webapp/node_modules/remap-istanbul/src/getMapping.js:19:26)
[INFO]     at getMappingResolved (webapp/node_modules/remap-istanbul/src/CoverageTransformer.js:159:20)
[INFO]     at remapFunction (webapp/node_modules/remap-istanbul/src/remapFunction.js:2:18)
[INFO]     at webapp/node_modules/remap-istanbul/src/CoverageTransformer.js:180:17
[INFO]     at Array.forEach (<anonymous>)
[INFO]     at CoverageTransformer.addFileCoverage (webapp/node_modules/remap-istanbul/src/CoverageTransformer.js:176:35)
```

Looks like remap-istanbul has a dependency on `"source-map": "^0.6.1",`.  This has pulled in the newest version of [source-map@7.0.0](https://github.com/mozilla/source-map/blob/master/CHANGELOG.md#070) released 3 days ago (1/20/18).

I tried adding a console log statement to see what kind of object the [sourceMap](https://github.com/SitePen/remap-istanbul/blob/master/src/getMapping.js#L9) is, but suprisingly nothing was dumped into the output.  I'm not entirely sure why...

Also, I have multiple dependencies pulling in `source-map`,
```
source-map@0.5.x, source-map@^0.5.1, source-map@^0.5.3, source-map@^0.5.6, source-map@~0.5.0, source-map@~0.5.1, source-map@~0.5.3, source-map@~0.5.6:
  version "0.5.7"
  resolved "https://registry.yarnpkg.com/source-map/-/source-map-0.5.7.tgz#8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc"

source-map@>=0.5.6:
  version "0.7.0"
  resolved "https://registry.yarnpkg.com/source-map/-/source-map-0.7.0.tgz#ebf0d13a48f3619f91891816fdda932f83a6021f"

source-map@^0.4.2, source-map@^0.4.4:
  version "0.4.4"
  resolved "https://registry.yarnpkg.com/source-map/-/source-map-0.4.4.tgz#eba4f5da9c0dc999de68032d8b4f76173652036b"
  dependencies:
    amdefine ">=0.0.4"

source-map@^0.6.1, source-map@~0.6.1:
  version "0.6.1"
  resolved "https://registry.yarnpkg.com/source-map/-/source-map-0.6.1.tgz#74722af32e9614e9c287a8d0bbde48b5e2f1a263"

source-map@~0.2.0:
  version "0.2.0"
  resolved "https://registry.yarnpkg.com/source-map/-/source-map-0.2.0.tgz#dab73fbcfc2ba819b4de03bd6f6eaa48164b3f9d"
  dependencies:
    amdefine ">=0.0.4"
```

And it seems that the one in the `node_modules` directory has been **resolved to 0.5.7**, which I'm guessing is ok, but probably wrong for remap-istanbul.  My ultimate guess is that the [utils/node](https://github.com/SitePen/remap-istanbul/blob/master/utils/node.js#L13) script is requesting for the wrong `source-map` dependency.

**Comment by mtraynham** [comment]
Oop just noticed #160, closing.

**Comment by dylans** [comment]
@mtraynham Yes, could you please verify if either 0.9.6 or 0.10.1 resolve this issue for you? Thanks!

**Comment by mtraynham** [comment]
@dylans It does work, thank you!
