### ISSUE TITLE
Mocha how-to?

### ISSUE THREAD

**Issue by JaKXz** [SitePen/remap-istanbul#17]
I arrived here looking for TypeScript coverage for my server-side code and my test runner is Mocha. Anyone know the easiest way to get coverage reports? If it helps, my `mocha.opts` looks like this:
```
--compilers ts:espower-typescript/guess
--require mocha.conf.ts
```

**Comment by novemberborn** [comment]
Hey @JaKXz, funny I just started adding coverage reports to my project (compiled through Babel). Work in progress but see the `bin/coverage.sh` script for my approach: <https://github.com/novemberborn/buoyant/pull/2>. 

I used `node_modules/.bin/_mocha` as the entry-point. It's what the `mocha` command runs in a child-process.

I couldn't really figure out how to use `remap-istanbul` to generate the HTML reports. Replacing the `coverage.son` that `istanbul` generated with a remapped version seemed to do the trick.

**Comment by kitsonk** [comment]
Hmmm...

@novemberborn in your `coverage.sh` did something like not work:

```sh
remap-istanbul -i coverage/coverage.json -o html-report -t html
```

If it didn't I need to look into it...  Also, I will try to add your approach to the Wiki.

**Comment by novemberborn** [comment]
@kitsonk actually that does work. It got very confusing trying to run multiple commands myself on the command line. I think I saw a crash earlier but maybe I was doing something wrong.

However `istanbul report` generates a `lcov.info` file which tools like <https://github.com/jacogr/atom-lcov-info> can use. Doesn't look like `remap-istanbul` can do that in a single command invocation, if at all?

---

I should also point out that my tests are exercising the transformed code as written to disk, e.g. without require hooks.

**Comment by kitsonk** [comment]
@novemberborn the following should work:

```sh
remap-istanbul -i coverage/coverage.json -o lcovonly -t lcov.info
```

It is a little bit confusing, but we are following the the report naming provided by Istanbul which uses that name.  `lcov` produces both a HTML report and an `lcov.info`.

**Comment by novemberborn** [comment]
@kitsonk calling with `remap-istanbul -i coverage/coverage.json -o iconv-only -t lcov` gives:

```
SyntaxError: Unrecognized report type of "lcov".
    at buoyant/node_modules/remap-istanbul/lib/writeReport.js:39:12
    at writeReport (buoyant/node_modules/remap-istanbul/lib/writeReport.js:37:10)
    at buoyant/node_modules/remap-istanbul/bin/remap-istanbul:126:11
```

Happy to discuss that in a separate issue, seems unrelated to the Mocha question as such.

**Comment by novemberborn** [comment]
This might be nicer with <https://github.com/bcoe/nyc> so you can do `nyc npm test`. That may be a nice general solution, even!

I'm trying that but suddenly https://github.com/SitePen/remap-istanbul/issues/19 is getting in the way. Not sure how it's related to the added `nyc` dependency though…

**Comment by novemberborn** [comment]
Here's my final (for now…) solution: <https://github.com/novemberborn/buoyant/blob/27abe5eec6dcd3612bd2715b281bdd4a0c31ba70/bin/coverage.sh>. It requires `nyc`, `istanbul` and `remap-istanbul` to be installed, and assumes tests are run via `npm test`. This should work for any test runner really.

**Comment by dylans** [comment]
Nice @novemberborn, that looks pretty easy to use!

**Comment by novemberborn** [comment]
I've written it up now: https://medium.com/@novemberborn/code-coverage-with-babel-istanbul-nyc-83b8c2f1093

**Comment by JaKXz** [comment]
Love it, thanks @novemberborn!
