### ISSUE TITLE
Node loader plugin loads modules that clobber the standard library

### ISSUE THREAD

**Issue by novemberborn** [SitePen/remap-istanbul#19]
If <https://www.npmjs.com/package/path> is installed next to `remap-istanbul` it'll be loaded instead of the normal `path` module. This is unexpected behavior, normal `require` usage wouldn't load that dependency.

I think it's due to this line <https://github.com/SitePen/remap-istanbul/blob/9c11633decc4081cde190e40f24df8b3bd8a8b64/lib/node.js#L13> which uses private API's to resolve the module path. I think this should be replaced by `require.resolve()`.

(And no I didn't choose to install that dependency, it's probably an accidental dependency of another dependency's dependency's dependency, flattened by npm@3.)

**Comment by kitsonk** [comment]
Good lord... "I have 180k packages and I don't know what they do for me..." :cry:

The node module here is adapted directly from the [dojo/dojo::node]() module, which is missing the comments of why this is there:

> The `nodeRequire` function comes from the Node.js module of the AMD loader, so module ID resolution is relative to the loader's path, not the calling AMD module's path. This means that loading Node.js modules that exist in a higher level or sibling path to the loader will cause those modules to fail to resolve.
>
> Node.js does not expose a public API for performing module filename resolution relative to an arbitrary directory root, so we are forced to dig into the internal functions of the Node.js `module` module to use Node.js's own path resolution code instead of having to duplicate its rules ourselves.
>
> Sooner or later, probably around the time that Node.js internal code is reworked to use ES6, the methods will no longer be exposed and we will have to find another workaround if they have not exposed  an API for doing this by then.

I don't thing `require.resolve()` works in the same fashion, as stated above, it is essentially `require()` but just returning the ID.  Considering though, this is just an internal helper versus a general purpose module, so we should be able to remove that logic.

**Comment by novemberborn** [comment]
Nice explanation, thanks.

Sounds like this would also be a bug in the `dojo/dojo::node` module though? Unfortunately npm doesn't disallow package names that conflict with the builtins.

**Comment by kitsonk** [comment]
> Sounds like this would also be a bug in the dojo/dojo::node module though?

It would seem so, in that it looks like we treat every MID as relative and try to remap it.  I suspect a potentially longer term fix is to detect if the MID is relative or absolute.  If it is absolute, then pass it through to `nodeRequire` unaltered and only remap those that are relative.

**Comment by bryanforbes** [comment]
@novemberborn Sorry for my confusion. I'm trying to come up with a scenario where `path` will be loaded and can't find one:

```
node_modules/
    a/
        node_modules/
            path/
        index.js <- contains `require('path')` and returns the builtin
        package.json <- contains "path" as a dependency
test.js <- contains `require('a')`
```

```
node_modules/
    a/
        index.js <- contains `require('path')` and returns the builtin
        package.json <- contains "path" as a dependency
    path/
test.js <- contains `require('a')`
```

If what you're saying is that node's require will never load a package named "path" (regardless of where it is located in the filesystem), then that's definitely a bug in `dojo/node`.

**Comment by novemberborn** [comment]
> If what you're saying is that node's require will never load a package named "path" (regardless of where it is located in the filesystem), then that's definitely a bug in dojo/node.

I believe that's the case, yes.

**Comment by kitsonk** [comment]
@novemberborn yes it impact Dojo 1, Dojo 2 and Intern as well.  I have installed the package as a dev dependency, which causes the issue to manifest and then modified the dojo/node module.  I have a couple of other things I want to get done before releasing 0.5.0 but master now has the fix.

**Comment by novemberborn** [comment]
Thanks!

I got an upstream fix in my other dependency's dependency dependency which removed the local `path` install so I'm good even without the 0.5.0 release.

**Comment by kitsonk** [comment]
If you want some fun, look at this [silliness](https://www.npmjs.com/browse/depended/fs).  Almost 400 packages that depend on a package that logs to console `"I'm 'fs' modules"`.  Idiots.
