### ISSUE TITLE
Allow for filtering files from a bundle when remapping

### ISSUE THREAD

**Issue by jpeters5392** [SitePen/remap-istanbul#23]
The karma-coverage module allows the developer to specify a file glob to indicate which files are going to be instrumented.  However, if we are running against a bundle we cannot specify which modules inside of the bundle are to be instrumented.  It would be nice if remap-instanbul allowed us to specify a file glob and when remapping the coverage report from a bundle it would only include mapped files that matched the glob.

**Comment by kitsonk** [comment]
I can see how that can be a challenge and it seems like a reasonable feature.  My instinct is to provide an exclusion regex of the source files... e.g. `exclude = /\/(tests|node_modules)\//;`

**Comment by jpeters5392** [comment]
@kitsonk That approach seems reasonable to me.

**Comment by kitsonk** [comment]
Ok, I added this feature...  For `remap` the option `exclude` can be a string or a Regular Expression and should look something like this:

```javascript
remap(loadCoverage('coverage.json'), {
    exclude: 'node_modules' // if the file path of the input coverage contains this at all it will be excluded
});

remap(loadCoverage('coverage.json'), {
  exclude: /node_modules/ // if the file path of the input coverage matches this regex it will be excluded
});
```

**Comment by nmn** [comment]
Can we have this for the output as well??

I'm using remap-istanbul as I transition to start using Browserify. As a result, I first generate a report for a bundled file, and then remap that to the original files using remap-istanbul.

It would be really awesome if I can exclude the original files that the sourcemap points to. The current option applies to the input files. The input files are usually one big bundle to begin with.
