### ISSUE TITLE
Allow the grunt task for remap to take options for warn property about missing source map file

### ISSUE THREAD

**Issue by aryelu** [SitePen/remap-istanbul#27]
Hi, I'm using this for displaying the coverage for a project with js and ts files together. I'd like to have the `remap` task to complete without `grunt.fail.warn` on it when reading a js file which doesn't have a source map. Can we add a severity flag in the grunt and remap function options for it?

**Comment by kitsonk** [comment]
Yes, I should be able to do that.  I will try to take a look at it this weekend and release a point release.

**Comment by kitsonk** [comment]
This was addressed specifically by 30b67ad3f24ba7e0da8b8888d5a7c3c8480d48b2 but I also did something similar for gulp in 0a44cc2d95e0d8a609aebbfa629c595639789f00 and it is published in release 0.5.1 which is the most current version on npm.

**Comment by aryelu** [comment]
Thanks alot
