### ISSUE TITLE
I get weird paths

### ISSUE THREAD

**Issue by Foxandxss** [SitePen/remap-istanbul#28]
I have a project using Typescript and to test it, I transpile all source and tests like:

```
temp/foo/foo.js
temp/foo/foo.js.map
temp/foo/foo.spec.js
```

A bunch of folders like that.

Original files are:

```
src/foo/foo.ts
src/foo/foo.spec.ts
```

I put `karma-coverage` and it works perfectly by running it against that temp folder (to process only .js file and not spec nor map files).

My `coverage-final` has path like:

```
"/Users/myuser/code/ng2/folder/anotherfolder/temp/foo/foo.js":{"path":"/Users/myuser/code/ng2/folder/anotherfolder/temp/foo/foo.js"
```

And the .map for that concrete file starts with:

```
{"version":3,"sources":["foo/foo.ts"]
```

When I run this tool (via CLI or gulp) I get in the result json:

```
"../../../../../../source/foo/foo.ts":{"path":"../../../../../../source/foo/foo.ts"
```

Notice all that `../` and then that `source` folder that comes from nowhere. Transpiled code is in `temp` and real source is in `src`.

Then if I try to convert this to html, it fails on the path.

Not sure if I am using this wrong or there is a bug.

**Comment by stevehipwell** [comment]
I'm also having this issue.

**Comment by bronzovik** [comment]
This comes from ```lib/remap.js getMapping```.
I managed to get command line working by changing path resolution in the return statement to:
```
source: process.cwd() + start.source,
```
Gulp plugin keeps failing with different broken paths though.

**Comment by bronzovik** [comment]
This is quick and dirty fix (tests fail) working from gulp. Paths resolution is changed in remap.js. I'm not sure if this is the right way to do things, because it obviously does not pass unit tests.
https://github.com/SitePen/remap-istanbul/compare/master...bronzovik:master?diff=split&name=master

**Comment by kitsonk** [comment]
> When I run this tool (via CLI or gulp) I get in the result json:

@Foxandxss can you provide your actual CLI command?

@bronzovik thanks for the effort...  I will try to fix it permanently.

**Comment by Foxandxss** [comment]
For example the one on the README: `cat coverage-final.json | ./node_modules/.bin/remap-istanbul -o coverage-remapped.json`

**Comment by joerideg** [comment]
I'm having the same issue with the same setup as @Foxandxss described (except of course some different file names). 
I run the following command on the coverage-final.json that karma-coverage outputs:
<code>remap-istanbul -i coverage/coverage-final.json -o coverage/coverage.json</code>

**Comment by joerideg** [comment]
@bronzovik when using your branch I do get to see all the files in the html coverage report and I can view them, it does somehow get them from the inital coverage-final.json output by karma-coverage. However it still tries to find them in a 'source' folder. e.g: 
```json
"/hippo-ngbp/dist/scripts/source/main.service.js":{"path":"/hippo-ngbp/dist/scripts/source/main.service.js"
```
that source folder isnt there actually so it suprises me that it actually shows the source code in the html report. Also the coverage percentage does not change when dropping some tests, even though it does put in a few red lines here and there.

**Comment by bronzovik** [comment]
@joerideg I have to look. Mind you that my fix is pretty dumb. It was an experiment to fix the path issue, but I'm sure It should be refined.

**Comment by dlebedynskyi** [comment]
any news on this issue? having same problems with weird '../..'

**Comment by joerideg** [comment]
Well I submitted a pull request but no response.

**Comment by dlebedynskyi** [comment]
@joerideg  yeah. I might have just to use your fork just for now. Hopefully this will be fixed quite soon

**Comment by dylans** [comment]
@kitsonk is out this week, I expect he'll review and land next week...

**Comment by joerideg** [comment]
Cool! Im happy to make any adjustments needed.

**Comment by jayku4u** [comment]
+1

**Comment by Foxandxss** [comment]
Any update? I would like to get this working for my projects :)

**Comment by kitsonk** [comment]
I am not sure if the handling of the `code` in the `coverage.json` is going to fix some/most of these issues.  I am going to release 0.6.0 and see if that helps these.

**Comment by kitsonk** [comment]
I think version 0.6.3 should (finally) handle issues when using sources from source maps and their paths.
