### ISSUE TITLE
cannot cope with inline sourcemaps when the path is absolute

### ISSUE THREAD

**Issue by lukeapage** [SitePen/remap-istanbul#29]
After upgrading from 0.4.0 I get these kind of messages

```
Fatal error: Unable to find entry for [src\file.js]
```

from the html report, when it generates the output.

Its like after 0.4.0 it is looking for the source files relative to a different directory?

any ideas?
Its either broken by this module or istanbuls 0.4.1 release..

**Comment by kitsonk** [comment]
How are you running remap-istanbul?  Is there a public repo where your project available?  What does your coverage.json and source maps look like?  Where is your original code relative to your built code?

**Comment by lukeapage** [comment]
I'm running it programmatically like this

```
function coverage() {
	var done = this.async();
	remapIstanbul(sharedConfig.dist + '/coverage/coverage.json', {
		'json': sharedConfig.dist + '/coverage/coverage-final.json',
		'html': sharedConfig.dist + '/coverage/',
		'text': null
	}).then(function () {
		done();
	});
}
```

when I run the same thing on the command line it works fine.. I'll investigate a bit more.

the structure is

/dist/release/file.js <-- tested output
/dist/coverage/ <-- coverage
/src/ <-- source

**Comment by lukeapage** [comment]
I've just switched to the grunt config and I get the error..

**Comment by lukeapage** [comment]
stack trace:
```
Error: Unable to find entry for [src\log.js]
    at MemoryStore.Store.mix.get (C:\Projects\Iit_Shared_JS\node_modules\istanbul\lib\store\memory.js:38:19)
    at HtmlReport.Report.mix.writeDetailPage (C:\Projects\Iit_Shared_JS\node_modules\istanbul\lib\report\html.js:411:67)
    at C:\Projects\Iit_Shared_JS\node_modules\istanbul\lib\report\html.js:489:26
    at SyncFileWriter.extend.writeFile (C:\Projects\Iit_Shared_JS\node_modules\istanbul\lib\util\file-writer.js:57:9)
    at FileWriter.extend.writeFile (C:\Projects\Iit_Shared_JS\node_modules\istanbul\lib\util\file-writer.js:147:23)
    at C:\Projects\Iit_Shared_JS\node_modules\istanbul\lib\report\html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (C:\Projects\Iit_Shared_JS\node_modules\istanbul\lib\report\html.js:482:23)
    at C:\Projects\Iit_Shared_JS\node_modules\istanbul\lib\report\html.js:484:22
    at Array.forEach (native)
```

**Comment by lukeapage** [comment]
Its between 0.4.0 and 0.5.0 the problem occurs in. force upgrading istanbul to 0.4.1 makes no difference to remap-istanbul 0.4.0

**Comment by lukeapage** [comment]
specifically it is introduced by this commit:
https://github.com/SitePen/remap-istanbul/commit/6c67bd3aba9af002c98a3f723a602789add45c7f

**Comment by lukeapage** [comment]
It seems my sourcemap has inline sources. These are absolute paths and I am on windows. When I log sources.map after being processed by remap, the paths that were in the sourcemap become

`C:\Projects\x\src\y\z\z.js`
=>
`dist\release\C:\Projects\x\src\y\z\z.js`

I guess previously when inline sources were not supported it just managed to find the file on disk fine and now it doesn't..

**Comment by lukeapage** [comment]
I can fix my case by adding this code

```
				/* if there are inline sources and a store to put them into, we will populate it */
				if (sourceMap.sourcesContent && sourceStore) {
					sourceMap.sourcesContent.forEach(function (source, idx) {
						var srcPath = sourceMap.sources[idx];
						if (path.isAbsolute(srcPath)) {
							srcPath = path.relative('', srcPath);
						} else {
							srcPath = path.join(sourceMapDir, srcPath);
						}
						sourceStore.set(srcPath, source);
					});
				}

```

in remap.js around line 204

wdyt ?

**Comment by lukeapage** [comment]
Note, I decided to make my sourcemaps relative, which fixes the problem, so this doesn't effect me any more

**Comment by kitsonk** [comment]
Thanks, sorry for the delayed response and that you have a workaround, but yeah we need to address it.

**Comment by bruno-garcia** [comment]
My sourcemaps have relative path and I still have this issue.
The fix posted by @lukeapage solved my problem though.

**Comment by JaKXz** [comment]
@kitsonk any update on this? I tried both inline and sibling source maps and I'm still seeing this error.

**Comment by kitsonk** [comment]
Version 0.6.3 should handle paths and sources from source maps properly now.
