### ISSUE TITLE
Add a CLI

### ISSUE THREAD

**Issue by blakeembrey** [SitePen/remap-istanbul#3]
It would be amazing if this could integrate with current Istanbul usages using the CLI to do something like:

```
istanbul cover node_modules/mocha/bin/_mocha -- dist/**/*.spec.ts --require typescript-node/register -R spec --bail && remap-istanbul
```

Where the CLI `remap-istanbul` assumes default output from `istanbul` by default to rewrite and can optionally accept a path, etc. to override the assumption.

Edit: Not that the code coverage works with that yet, that's another issue to fix with istanbul.

**Comment by kitsonk** [comment]
Yeah, I realised we had forgotten to do that and it is quite logical.
