### ISSUE TITLE
js files without source-map to change from absolute path to relative

### ISSUE THREAD

**Issue by aryelu** [SitePen/remap-istanbul#32]
We're using remapIstnabul for coverage of a project with `js` and `ts` files, I'd like the `js` files coverage, (which aren't with a source-map) path to be relative to my `process.cwd()` (or to take an argument)

I'd change in `remap.js`:
`srcCoverage[filePath] = fileCoverage;`
to:
`srcCoverage[path.relative(process.cwd(), filePath)] = fileCoverage;`

**Comment by kitsonk** [comment]
So you have coverage information that doesn't need to be remapped?  Logically I would have thought we would just copy the path and not touch it, though I know I made changes to deal with properly handling files without coverage and may have touched the paths.

Mixed projects are obviously becoming challenging and I may need to figure out if it is necessary to expose some options to manage this better.

**Comment by aryelu** [comment]
We use `js` and `ts`, and we'd like the coverage report to appear as the original folder structure before the typescript compilation. 

You have the following in `getMapping` which determines the original path:
```js
source: path.relative(process.cwd(), path.resolve(sourceMapDir, start.source)),
```
It should work on the non source mapped path in the same manner,
maybe the `fileCoverage` object should update also:

```js
fileCoverage.path = path.relative(process.cwd(), fileCoverage.path);
srcCoverage[path.relative(process.cwd(), filePath)] = fileCoverage;
```

**Comment by kitsonk** [comment]
I am not sure this is relevant with the changes to how file names are resolved when using sources from source maps.  Could you check out 0.6.3 and see if fixes your use case as well?

**Comment by kitsonk** [comment]
I am going to rework the whole name resolution logic in `0.7.0` because it is far more complicated than it appears on the surface.

**Comment by dylans** [comment]
Is this still an issue with 0.8.4? I don't think we did a full name resolution logic rewrite, but we've done a number of path logic related fixes since this issue was opened.

**Comment by dylans** [comment]
Closing as I believe this works with 0.8.4 and later. If not, please reopen.
