### ISSUE TITLE
remap-istanbul binary doesn't use inline sources

### ISSUE THREAD

**Issue by Arnavion** [SitePen/remap-istanbul#33]
Assume `G:\src\libjass` is the root of my project, TypeScript source files are under src/ (eg: `G:\src\libjass\src\parser\index.ts`), the transpiled JS being instrumented and its sourcemap are under lib/ (`G:\src\libjass\lib\libjass.js` and `G:\src\libjass\lib\libjass.js.map`), and the coverage file generated with the intern reporter is at `G:\src\libjass\coverage-final.json`

The coverage file and sourcemap are at https://gist.github.com/Arnavion/0c3c71eaafdcf60de145 . As you can see, the sourcemap contains filenames relative to `G:\src\libjass\src` (eg: `parser/index.ts`) and corresponding source contents.

Now I run remap-istanbul in the `G:\src\libjass` directory as `./node_modules/.bin/remap-istanbul -i ./coverage-final.json -t html -o html-report` and the html reporter complains about being unable to find `G:\src\libjass\lib\index.ts`. It's correct that that file does not exist (it's looking under lib/, not src/) and I could fix this by passing in `-b ./src`, but it shouldn't need to look for the files anyway since they're inlined in the sourcemap.

---

The remap-istanbul binary calls `writeReport` as

``` javascript
if (output) {
    return writeReport(collector, reportType || 'json', output);
}
```

which is missing the fourth parameter to writeReport - the source store parameter. As a result the HtmlReport reporter creates an `fslookup` source store which expects the source files to exist.

I changed the binary to use a `memory` Store for the `options.sources` property so that `remap` would populate it:

``` javascript
var Store = require('../node_modules/istanbul/lib/store');
...
var sourceStore = Store.create('memory');
...
var collector = remap(coverage, basePath ? {
    basePath: basePath
} : { sources: sourceStore }); // <--
/* istanbul ignore else: too hard to test writing to stdout */
if (output) {
    return writeReport(collector, reportType || 'json', output, sourceStore); // <--
}
```

---

The next problem is that the store is loaded with full paths as the keys in `remap`:

``` javascript
sourceStore.set(path.join(sourceMapDir, sourceMap.sources[idx]), source);
// The result of path.join is an absolute path like "G:\src\libjass\lib\parser\index.ts" because sourceMapDir is the absolute path "G:\src\libjass\lib". Note that this doesn't point to the original file which is under src/
```

... but the html reporter later looks them up using relative keys. It gets these relative paths from the collector's store which is also populated in `remap` but in a different way:

``` javascript
collector.add(srcCoverage);
// All the keys of srcCoverage are relative paths like "lib\parser\index.ts" because that's how it's populated in getSourceCoverage()
```

So again it fails to find the files in the in-memory source store and complains.

Changing the `sourceStore.set` line to not use `path.join` doesn't help because then the collector contains keys with `\` as the path separator (from `getMapping` because it uses `path.relative`) and the reporter looks up keys with `/` as the path separator (from the store).

So I changed it to `sourceStore.set(path.relative('.', path.join(sourceMapDir, sourceMap.sources[idx])), source);` and it works\* but makes me want to wash my hands with soap.

(*) The coverage report lists all the TS files as if they're under lib/ instead of src/, but it has no way of knowing otherwise so I don't mind.

**Comment by kitsonk** [comment]
Several things here...  Need to go through this with a fine tooth comb.

**Comment by Arnavion** [comment]
To be fair, it's not a bug unless you try to code the enhancement like I did, i.e., change the `sourceStore.set` call to not use `path.join`. I'll take that out of the title.

No matter how you decide to code the enhancement, as long as it consistently uses `path` functions for everything it'll be fine.

**Comment by kitsonk** [comment]
I think b71425492471fc2f3934af3b085d0f980bb7ef1d might have addressed the bulk of this.  If the source code can be found (e.g. via the `code` property of the `coverage.json`) it won't go looking further for it and if it finds inlined source code, it will output the original source in the `code` property.

**Comment by Arnavion** [comment]
I've installed remap-istanbul@0.6.1 and the two files in the gist in the OP still give the same error.

As you can see there is no `code` property in `coverage-final.json`

**Comment by kitsonk** [comment]
Ok, I will dig into it further, as it seems that while I am parsing out the source out of the source-maps properly, the HTML reporter is not seeing them.  It populates a source store for Istanbul, that doesn't seem to be working with the HTML Reporter.  I think I have enough to get a test case working for that now.  Thanks.

**Comment by Arnavion** [comment]
Yes, that's what the OP says :)

**Comment by kitsonk** [comment]
I realise that, but trying to write things out in a way I can remember what I was actually thinking and digesting at the time 😄 my brain doesn't work so good...

**Comment by Arnavion** [comment]
(I should add that in the months since I opened this issue, TS added `--outFile` support for concatenating AMD modules and I switched to the sourcemap it generates instead of building my own. This new sourcemap contains source paths relative to the output directory. `"parser/parse.ts"` is now `"../src/parser/parse.ts"`, and so on. So the default `fslookup` store is able to locate the files and the command in the OP doesn't throw the error any more.)

**Comment by kitsonk** [comment]
Ok, it appears when the inline source support for reports was added, it wasn't added to the CLI.  I have added it now.  It is transparent, so it should "just work" now.  Apologies for taking so long and being thick on understanding.

**Comment by Arnavion** [comment]
```
PS [02:11:26] G:\src\libjass> ./node_modules/.bin/remap-istanbul -i ./coverage-final.json -t html -o html-report
G:\src\libjass\node_modules\remap-istanbul\node_modules\istanbul\lib\store\memory.js:38
            throw new Error('Unable to find entry for [' + key + ']');
            ^

Error: Unable to find entry for [lib\index.ts]
    at MemoryStore.Store.mix.get (G:\src\libjass\node_modules\remap-istanbul\node_modules\istanbul\lib\store\memory.js:38:19)
    at HtmlReport.Report.mix.writeDetailPage (G:\src\libjass\node_modules\remap-istanbul\node_modules\istanbul\lib\report\html.js:411:67)
    at G:\src\libjass\node_modules\remap-istanbul\node_modules\istanbul\lib\report\html.js:489:26
    at SyncFileWriter.extend.writeFile (G:\src\libjass\node_modules\remap-istanbul\node_modules\istanbul\lib\util\file-writer.js:57:9)
    at FileWriter.extend.writeFile (G:\src\libjass\node_modules\remap-istanbul\node_modules\istanbul\lib\util\file-writer.js:147:23)
    at G:\src\libjass\node_modules\remap-istanbul\node_modules\istanbul\lib\report\html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (G:\src\libjass\node_modules\remap-istanbul\node_modules\istanbul\lib\report\html.js:482:23)
    at G:\src\libjass\node_modules\remap-istanbul\node_modules\istanbul\lib\report\html.js:484:22
    at Array.forEach (native)
```

From the OP:

>The next problem is that the store is loaded with full paths as the keys in `remap` ... but the html reporter later looks them up using relative keys.

**Comment by kitsonk** [comment]
Bugger... 😢

**Comment by kitsonk** [comment]
ok, what I need to do is not modify the `sourceMap.sources` entries when remapping when there is content... working on that now

**Comment by kitsonk** [comment]
Ok, I think I figured it out and should be in 0.6.3.  Essentially, if there is an inline source, I don't attempt to remap it (since we don't need to), so whatever the source-map filename resolves to, is what will be placed in the source store for the report to be written out.

**Comment by kitsonk** [comment]
I think this works, so closing unless someone says otherwise, although I am going to rework the whole name resolution stuff in 0.7.0 because it causes all sorts of chaos and everything is pretty hacky at the moment.

**Comment by dylans** [comment]
I believe this has been working for a while now hopefully. Please open issues on anything we're not getting right with inline source maps.
