### ISSUE TITLE
Incorrect Mapping

### ISSUE THREAD

**Issue by iamchairs** [SitePen/remap-istanbul#40]
I'm looking at the source code now but just in case this is something I'm doing wrong the mapping is completely off. I have one concatenated typescript file with all sourcemaps 64base encoded at the bottom. The first record in the source map appears to be:

`"components/log/log.service.ts"`

But in the remapped json it appears as:

`"../../../../../../app/components/log/log.service.ts"`

I'm not sure why this is. But hopefully I can figure that out soon. Here is my gulp task to run remap-istanbul:

    var remapIstanbul = require('remap-istanbul/lib/gulpRemapIstanbul');

    module.exports = function (gulp, config) {

       gulp.task('coverage', [
          //'test'
       ], function() {
          return gulp.src(config.paths.coverage)
            .pipe(remapIstanbul({
              reports: {
                json: './coverage/coverage-final.json',
                html: './coverage/html-report'
              }
            }));
       });

    };

**Comment by jayku4u** [comment]
Were you able to workaround this bug?

**Comment by iamchairs** [comment]
Yes I had to hack it.

```
gulp.task('coverage', [
      'test'
   ], function() {
    
      // HACK: this makes absolute paths relative
      
      var coverage = JSON.parse(fs.readFileSync(config.paths.coverage));
      var redirectedCoverage = {};
      for(var key in coverage) {
        var keys = key.split(/[\/\\]/g);
        var newKeyParts = [];
        var keyPart;

        while(keyPart = keys.pop()) {
          newKeyParts.unshift(keyPart);
          if(keyPart === 'www') {
            break;
          }
        }

        redirectedCoverage[newKeyParts.join('/')] = coverage[key];
      }
      fs.writeFileSync(config.paths.coverage, JSON.stringify(redirectedCoverage));

      // END HACK

      return gulp.src(config.paths.coverage)
        .pipe(remapIstanbul({
          reports: {
            json: './coverage/coverage-final.json',
            html: './coverage/html-report'
          }
        }));
   });
```

Not sure what I did but I eventually got them to use absolute paths.

**Comment by kitsonk** [comment]
Version `0.6.3`, when using sources from source maps no longer tries to remap the file names.  In addition, there is the `useAbsolutePaths` configuration option as well.
