### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by nbering** [SitePen/remap-istanbul#52]
Error output as below when processing a coverage file from TypeScrupt-compiled js that uses `--outFile`, plus a couple of non-sourcemapped .js files. I had attempted to integrate this project a while back but had issues and moved on/didn't get coverage reports working. Trying again. I just wanted to make sure this gets reported and help debug this issue further if it's not a known issue.

Input:
```
$ cat coverage/coverage.json | ./node_modules/.bin/remap-istanbul -o coverage/coverage-remap.json
```
Output:
```
TypeError: Cannot convert undefined or null to object
    at <My Project Directory>/node_modules/remap-istanbul/lib/remap.js:182:11
    at Array.forEach (native)
    at remap (<My Project Directory>/node_modules/remap-istanbul/lib/remap.js:181:12)
    at <My Project Directory>/node_modules/remap-istanbul/bin/remap-istanbul:131:19
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Environment:
- typescript: 1.8.9
  - occurs with both `--inlineSourceMaps` and `--sourceMap` flags
- node: 6.0.0
- OS: OS X El Capitan 10.11.4
- istanbul: 0.4.3
  - using `instanbul cover` command
- remap-istanbul: 0.6.3

I'm not authorized to spend work hours on this without confirmation that the issue is unreported and unknown, so please get back to me if you need more info. Thank you.

**Comment by kitsonk** [comment]
As far as I am aware it is unreported or unknown... I will take a look in a bit.

**Comment by kitsonk** [comment]
It would seem like we hadn't actually had anyone use the stdin for the CLI as it didn't read the coverage properly.  It needed to do an extra processing step which mirrors the `loadCoverage.js` functionality.  Anyways, it is fixed now in master.

**Comment by nbering** [comment]
Thanks.
