### ISSUE TITLE
Undocumented breaking change in writeReport()

### ISSUE THREAD

**Issue by mhoyer** [SitePen/remap-istanbul#53]
With [this commit](https://github.com/SitePen/remap-istanbul/commit/d07ac8c439a724d0e3aeb748938ee73a07451614#diff-f88ce483559c3246ce2dc72a8a3acf35R54) an additional parameter was introduced for `writeReport()` function, but the [documentation is missing an update](https://github.com/SitePen/remap-istanbul/blob/master/README.md#libwritereport).

**Comment by dylans** [comment]
PR at https://github.com/SitePen/remap-istanbul/pull/124
