### ISSUE TITLE
Console Output

### ISSUE THREAD

**Issue by steve-gray** [SitePen/remap-istanbul#58]
The documentation needs to be updated to reflect that if you want to have console output written from text/text-summary, you need to pass a null filename. This caused much strife trying to figure things out today!

**Comment by bdonald25** [comment]
@steve-gray I am having trouble getting it to output a text-summary to console. How do I pass it a null filename?

"remap-istanbul -b src/ -i coverage/coverage-final.json --exclude scripts,index.ts,testing -o --type text-summary"
I am trying this with no option following -o but it throws an error. If I do not include the -o then it prints to console but it is not a text-summary .  If  I include a filename after the -o then it correctly outputs a text-summary to that file. However, I can't figure out how to output a text-summary to the console. It seems to ignore the --type unless the output is a file.

**Comment by gabrielaraujof** [comment]
@steve-gray How did you manage to have console output from `text-summary` type? 
I'm using karma-remap-istanbul plugin and even with `null` filename I didn't get any console output.

Taking a look at the [writeReport](https://github.com/SitePen/remap-istanbul/blob/master/lib/writeReport.js) source code, I notice that only `text-lcov` can have a logging function. But I have no clue why this limitation exists.

**Why `text-summary` reporter can't handle a logging function as well?**

**Comment by aarmora** [comment]
@steve-gray I would also love to know how you are doing this. Echoing what @bdonald25 and @gabrielaraujof have said, I can't get any results in the console.

**Comment by steve-gray** [comment]
It's been a long, long time since I did this and I can't remember how exactly. The long and short of the story was that I switched to NYC instead of using Istanbul + Plugins to arrange things - completely sidestepping the issue and leveraging the inbuilt remapping.
