### ISSUE TITLE
How can I get this to work with Karma?

### ISSUE THREAD

**Issue by onlywei** [SitePen/remap-istanbul#6]
I followed this blog post to find Isparta and the gotwarlost/istanbul.git#source-map branch.

https://medium.com/@gunnarlium/es6-code-coverage-with-babel-jspm-karma-jasmine-and-istanbul-2c1918c5bb23

I noticed that you posted this project into this issue: https://github.com/gotwarlost/istanbul/issues/212

However, all the documentation on the README seems quite alien to me. Is this project really doing the same thing as Istanbul's #source-map branch?

**Comment by kitsonk** [comment]
As stated in the [Contribution Guidelines](../blob/master/CONTRIBUTING.md) we keep the issues on GitHub focused on bugs and enhancements and we answer questions on [StackOverflow](https://stackoverflow.com/questions/ask/advice?tags=remap-istanbul).

**Comment by alawatthe** [comment]
I agree, that questions should be on StackOverflow. However a short documentation (like the ones for grunt and gulp) for karma in the Readme would be great.

**Comment by kitsonk** [comment]
I am updating the wiki to join up using the coverage information from Istanbul from the command line, but I think it will be challenging to cover everything that uses Istanbul.

**Comment by kitsonk** [comment]
The wiki has been updated with a [How To for Karma](../wiki/Karma-How-To).

**Comment by alawatthe** [comment]
Awesome! Thanks :-D
