### ISSUE TITLE
Gulp Plugin - enforceThresholds

### ISSUE THREAD

**Issue by steve-gray** [SitePen/remap-istanbul#61]
The gulp plugin requires an enforceThresholds capability, similiar to gulp-istanbul. Without this people have to write custom code in the on('end') for their pipe, and then reload the lcov data to make the determination about coverage.

**Comment by clementcur** [comment]
+1
The watermarks config option is working OK through the gulp plugin, but the check option isn't taken into account for some reason.
https://github.com/karma-runner/karma-coverage/blob/master/docs/configuration.md#check

**Comment by nainslie** [comment]
I'm looking into this as it's something I need for a project.  As my pipeline uses the karma-coverage plugin, I'm looking first at the way that karma-coverage does the threshold specification.  

Following [their syntax](https://github.com/karma-runner/karma-coverage/blob/master/docs/configuration.md#check), we could do something like:

```
return gulp.src('tests/coverage/coverage-final.json')
        .pipe(remapIstanbul({
            check: {
                global: {
                    statements: 50,
                    branches: 50,
                    functions: 50,
                    lines: 50,
                    excludes: [
                        'foo/bar/**/*.js'
                    ]
                },
                each: {
                    statements: 50,
                    branches: 50,
                    functions: 50,
                    lines: 50,
                    excludes: [
                        'other/directory/**/*.js'
                    ],
                    overrides: {
                        'baz/component/**/*.js': {
                            statements: 98
                        }
                    }
                }            
            },
            reports: {
                'html': 'tests/coverage/html-report',
                'cobertura': 'tests/coverage/cobertura-coverage.xml',
                'json': 'tests/coverage/coverage-remapped.json'
            }
        }));
```

Anyone have any opinion on this syntax/feature set?  Does it make sense to put it somewhere other than the gulp plugin?

**Comment by dylans** [comment]
@nainslie I don't have a strong opinion. Should we update the documentation about Gulp usage or do something else with this?
