### ISSUE TITLE
inlineSources true, generates output in wrong location

### ISSUE THREAD

**Issue by Kavorka79** [SitePen/remap-istanbul#63]
when inlining source with map-file the output gets spred out over multiple folders and report page css stops working. here is the index page

**_Changed to running remap in a gulp task since karma couldn't remap on first run...**_

![image](https://cloud.githubusercontent.com/assets/17569901/15576186/f211b012-2356-11e6-9eac-d90ce5a21a50.png)

tsconfig.json

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "inlineSources": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "./wwwroot/app/"
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}
```

karma:

```
        preprocessors: {
            "wwwroot/**/!(*spec).js": "coverage"
        },


        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ["progress", "coverage"],

        // default value
        coverageReporter:
        {
            includeAllSources: true,
            type: "json",
            dir: "coverage",
            subdir: "json",
            file: "coverage-final.json"
        },
```

gulp:

```
gulp.task("remap-to-typescript", function() {
    gulp.src("coverage/json/coverage-final.json")
        .pipe(remapIstanbul({
            reports: {
                html: "coverage/html"
            }
        }));
});
```

inlineSource will cause html pages from typescript files to be written in strange folder locations.

```
---ApplicationFolder
    |---app(generated by remap-istanbul *other source files deeper in the tree*)
    |---src 
         |---app(generated by remap-istanbul)
              |---BackendApi
                   |---backendCaller.service.ts.html
         |---Name of App       
              |---coverage
              |---json
                   |---coverage-final.json
              |---html
                   |---index.html
              |---wwwroot
                   |---BackendApi
                        |---backendCaller.service.js
                        |---backendCaller.service.js.map
              |---app
                   |---BackendApi
                        |---backendCaller.service.ts
```

Without inlineSources:

```
---ApplicationFolder
    |---src 
         |---Name of App       
              |---coverage
              |---json
                   |---coverage-final.json
              |---html
                   |---app(generated by remap-istanbul *follows app structure*)
                        |---BackendApi
                             |---backendCaller.service.ts.html
                   |---index.html
              |---wwwroot
                   |---BackendApi
                        |---backendCaller.service.js
                        |---backendCaller.service.js.map
              |---app
                   |---BackendApi
                        |---backendCaller.service.ts
```

map file with inlineSource:
`n":3,"file":"backendCaller.service.js","sourceRoot":"","sources":["../../../app/BackendApi/backendCaller.service.ts"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;YASA;gBAEI,uBAAoB,IAAU;oBAFlC,iBAwCC;oBAtCuB,SAAI,GAAJ,IAAI,CAAM;oBAGvB,SAAI,GAAG,UAAC,CAAiB;wBAC5B,MAAM,CAAC,IAAI,CAAC;oBAChB,CAAC,CAAC;oBAEK,cAAS,GAAG,UAAU,KAAsB;wBAC/C,IAAI,SAAS,GAAG,KAAI,CAAC,OAAO,CAAC,KAAK,CAAC,CAAC;wBACpC,IAAI,GAAG,GAAG,eAAa,SAAW,CAAC;wBACnC,MAAM,CAAC,KAAI,CAAC,QAAQ,CAAU,GAAG,EAAE,KAAK,CAAC,CAAC;oBAC9C,CAAC,CAAC;oBAEK,gBAAW,GAAG,UAAC,OAAiB;wBACnC,IAAI,WAAW,GAAG,KAAI,CAAC,OAAO,CAAC,OAAO,CAAC,CAAC;wBACxC,IAAI,GAAG,GAAG,iBAAe,WAAa,CAAC;wBACvC,MAAM,CAAC,KAAI,CAAC,QAAQ,CAAkB,GAAG,EAAE,OAAO,CAAC,CAAC;oBACxD,CAAC,CAAC;oBAEM,aAAQ,GAAG,UAAU,GAAW,EAAE,IAAS;wBAC/C,IAAI,UAAU,GAAG,KAAI,CAAC,IAAI,CAAC,IAAI,CAAC,GAAG,EAAE,IAAI,CAAC,SAAS,CAAC,IAAI,CAAC,EAAE,KAAI,CAAC,MAAM,EAAE,CAAC;6BACpE,GAAG,CAAU,UAAA,QAAQ,IAAI,OAAA,QAAQ,CAAC,IAAI,EAAE,EAAf,CAAe,CAAC,CAAC;wBAC/C,MAAM,CAAC,UAAU,CAAC;oBACtB,CAAC,CAAC;oBAEM,YAAO,GAAG,UAAC,MAAW;wBAC1B,IAAI,KAAK,GAAG,oBAAoB,CAAC;wBACjC,IAAI,OAAO,GAAG,CAAC,KAAK,CAAC,CAAC,IAAI,CAAC,MAAM,CAAC,WAAW,CAAC,QAAQ,EAAE,CAAC,CAAC;wBAC1D,MAAM,CAAC,CAAC,OAAO,IAAI,OAAO,CAAC,MAAM,GAAG,CAAC,CAAC,GAAG,OAAO,CAAC,CAAC,CAAC,GAAG,EAAE,CAAC;oBAC7D,CAAC,CAAC;oBAEM,WAAM,GAAG;wBACb,IAAI,OAAO,GAAG,IAAI,cAAO,EAAE,CAAC;wBAC5B,OAAO,CAAC,MAAM,CAAC,cAAc,EAAE,kBAAkB,CAAC,CAAC;wBACnD,MAAM,CAAC,IAAI,qBAAc,CAAC,EAAE,OAAO,EAAE,OAAO,EAAE,CAAC,CAAC;oBACpD,CAAC,CAAC;gBAlCF,CAAC;gBAJL;oBAAC,iBAAU,EAAE;;iCAAA;gBAyCb,oBAAC;YAAD,CAAC,AAxCD,IAwCC;YAxCD,yCAwCC,CAAA","sourcesContent":["﻿import {Injectable} from \"angular2/core\";\r\nimport {Http, Headers, RequestOptions} from \"angular2/http\";\r\nimport {Observable} from \"rxjs/Observable\";\r\nimport \"rxjs/Rx\";\r\nimport {IQuery} from \"../GeneratedFiles/IQuery\";\r\nimport {ICommand} from \"../GeneratedFiles/ICommand\";\r\nimport {CommandResponse} from \"../GeneratedFiles/CommandResponse\";\r\n\r\n@Injectable()\r\nexport class BackendCaller {\r\n\r\n    constructor(private http: Http) {\r\n    }\r\n\r\n    public test = (q: IQuery<string>): Observable<string> => {\r\n        return null;\r\n    };\r\n\r\n    public sendQuery = <TResult>(query: IQuery<TResult>): Observable<TResult> => {\r\n        var queryName = this.getName(query);\r\n        var url =`api/query/${queryName}`;\r\n        return this.httpPost<TResult>(url, query);\r\n    };\r\n\r\n    public sendCommand = (command: ICommand): Observable<CommandResponse> => {\r\n        var commandName = this.getName(command);\r\n        var url =`api/command/${commandName}`;\r\n        return this.httpPost<CommandResponse>(url, command);\r\n    };\r\n\r\n    private httpPost = <TResult>(url: string, data: any): Observable<TResult> => {\r\n        var observable = this.http.post(url, JSON.stringify(data), this.header())\r\n            .map<TResult>(response => response.json());\r\n        return observable;\r\n    };\r\n\r\n    private getName = (action: any): string => {\r\n        var regex = /function (.{1,})\\(/;\r\n        var results = (regex).exec(action.constructor.toString());\r\n        return (results && results.length > 1) ? results[1] : \"\";\r\n    };\r\n\r\n    private header = () => {\r\n        var headers = new Headers();\r\n        headers.append(\"Content-Type\", \"application/json\");\r\n        return new RequestOptions({ headers: headers });\r\n    };\r\n\r\n\r\n}"]}`

map-file without inlineSource:
`{"version":3,"file":"backendCaller.service.js","sourceRoot":"","sources":["../../../app/BackendApi/backendCaller.service.ts"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;YASA;gBAEI,uBAAoB,IAAU;oBAFlC,iBAwCC;oBAtCuB,SAAI,GAAJ,IAAI,CAAM;oBAGvB,SAAI,GAAG,UAAC,CAAiB;wBAC5B,MAAM,CAAC,IAAI,CAAC;oBAChB,CAAC,CAAC;oBAEK,cAAS,GAAG,UAAU,KAAsB;wBAC/C,IAAI,SAAS,GAAG,KAAI,CAAC,OAAO,CAAC,KAAK,CAAC,CAAC;wBACpC,IAAI,GAAG,GAAG,eAAa,SAAW,CAAC;wBACnC,MAAM,CAAC,KAAI,CAAC,QAAQ,CAAU,GAAG,EAAE,KAAK,CAAC,CAAC;oBAC9C,CAAC,CAAC;oBAEK,gBAAW,GAAG,UAAC,OAAiB;wBACnC,IAAI,WAAW,GAAG,KAAI,CAAC,OAAO,CAAC,OAAO,CAAC,CAAC;wBACxC,IAAI,GAAG,GAAG,iBAAe,WAAa,CAAC;wBACvC,MAAM,CAAC,KAAI,CAAC,QAAQ,CAAkB,GAAG,EAAE,OAAO,CAAC,CAAC;oBACxD,CAAC,CAAC;oBAEM,aAAQ,GAAG,UAAU,GAAW,EAAE,IAAS;wBAC/C,IAAI,UAAU,GAAG,KAAI,CAAC,IAAI,CAAC,IAAI,CAAC,GAAG,EAAE,IAAI,CAAC,SAAS,CAAC,IAAI,CAAC,EAAE,KAAI,CAAC,MAAM,EAAE,CAAC;6BACpE,GAAG,CAAU,UAAA,QAAQ,IAAI,OAAA,QAAQ,CAAC,IAAI,EAAE,EAAf,CAAe,CAAC,CAAC;wBAC/C,MAAM,CAAC,UAAU,CAAC;oBACtB,CAAC,CAAC;oBAEM,YAAO,GAAG,UAAC,MAAW;wBAC1B,IAAI,KAAK,GAAG,oBAAoB,CAAC;wBACjC,IAAI,OAAO,GAAG,CAAC,KAAK,CAAC,CAAC,IAAI,CAAC,MAAM,CAAC,WAAW,CAAC,QAAQ,EAAE,CAAC,CAAC;wBAC1D,MAAM,CAAC,CAAC,OAAO,IAAI,OAAO,CAAC,MAAM,GAAG,CAAC,CAAC,GAAG,OAAO,CAAC,CAAC,CAAC,GAAG,EAAE,CAAC;oBAC7D,CAAC,CAAC;oBAEM,WAAM,GAAG;wBACb,IAAI,OAAO,GAAG,IAAI,cAAO,EAAE,CAAC;wBAC5B,OAAO,CAAC,MAAM,CAAC,cAAc,EAAE,kBAAkB,CAAC,CAAC;wBACnD,MAAM,CAAC,IAAI,qBAAc,CAAC,EAAE,OAAO,EAAE,OAAO,EAAE,CAAC,CAAC;oBACpD,CAAC,CAAC;gBAlCF,CAAC;gBAJL;oBAAC,iBAAU,EAAE;;iCAAA;gBAyCb,oBAAC;YAAD,CAAC,AAxCD,IAwCC;YAxCD,yCAwCC,CAAA"}`

**Comment by Kavorka79** [comment]
Changed to running remap in a gulp task since karma couldn't remap on first run...

inlineSource will cause html pages from typescript files to be written in strange folder locations.
```
---ApplicationFolder
    |---app(generated by remap-istanbul *other source files deeper in the tree*)
    |---src 
         |---app(generated by remap-istanbul)
              |---BackendApi
                   |---backendCaller.service.ts.html
         |---Name of App       
              |---coverage
              |---json
                   |---coverage-final.json
              |---html
                   |---index.html
              |---wwwroot
                   |---BackendApi
                        |---backendCaller.service.js
                        |---backendCaller.service.js.map
              |---app
                   |---BackendApi
                        |---backendCaller.service.ts
```
Without inlineSources:
---ApplicationFolder
    |---src 
         |---Name of App       
              |---coverage
              |---json
                   |---coverage-final.json
              |---html
                   |---app(generated by remap-istanbul *follows app structure*)
                        |---BackendApi
                             |---backendCaller.service.ts.html
                   |---index.html
              |---wwwroot
                   |---BackendApi
                        |---backendCaller.service.js
                        |---backendCaller.service.js.map
              |---app
                   |---BackendApi
                        |---backendCaller.service.ts

karma:
```
        preprocessors: {
            "wwwroot/**/!(*spec).js": "coverage"
        },


        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ["progress", "coverage"],

        // default value
        coverageReporter:
        {
            includeAllSources: true,
            type: "json",
            dir: "coverage",
            subdir: "json",
            file: "coverage-final.json"
        },
```
gulp:
```
gulp.task("remap-to-typescript", function() {
    gulp.src("coverage/json/coverage-final.json")
        .pipe(remapIstanbul({
            reports: {
                html: "coverage/html"
            }
        }));
});
```

map file with inlineSource:
`n":3,"file":"backendCaller.service.js","sourceRoot":"","sources":["../../../app/BackendApi/backendCaller.service.ts"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;YASA;gBAEI,uBAAoB,IAAU;oBAFlC,iBAwCC;oBAtCuB,SAAI,GAAJ,IAAI,CAAM;oBAGvB,SAAI,GAAG,UAAC,CAAiB;wBAC5B,MAAM,CAAC,IAAI,CAAC;oBAChB,CAAC,CAAC;oBAEK,cAAS,GAAG,UAAU,KAAsB;wBAC/C,IAAI,SAAS,GAAG,KAAI,CAAC,OAAO,CAAC,KAAK,CAAC,CAAC;wBACpC,IAAI,GAAG,GAAG,eAAa,SAAW,CAAC;wBACnC,MAAM,CAAC,KAAI,CAAC,QAAQ,CAAU,GAAG,EAAE,KAAK,CAAC,CAAC;oBAC9C,CAAC,CAAC;oBAEK,gBAAW,GAAG,UAAC,OAAiB;wBACnC,IAAI,WAAW,GAAG,KAAI,CAAC,OAAO,CAAC,OAAO,CAAC,CAAC;wBACxC,IAAI,GAAG,GAAG,iBAAe,WAAa,CAAC;wBACvC,MAAM,CAAC,KAAI,CAAC,QAAQ,CAAkB,GAAG,EAAE,OAAO,CAAC,CAAC;oBACxD,CAAC,CAAC;oBAEM,aAAQ,GAAG,UAAU,GAAW,EAAE,IAAS;wBAC/C,IAAI,UAAU,GAAG,KAAI,CAAC,IAAI,CAAC,IAAI,CAAC,GAAG,EAAE,IAAI,CAAC,SAAS,CAAC,IAAI,CAAC,EAAE,KAAI,CAAC,MAAM,EAAE,CAAC;6BACpE,GAAG,CAAU,UAAA,QAAQ,IAAI,OAAA,QAAQ,CAAC,IAAI,EAAE,EAAf,CAAe,CAAC,CAAC;wBAC/C,MAAM,CAAC,UAAU,CAAC;oBACtB,CAAC,CAAC;oBAEM,YAAO,GAAG,UAAC,MAAW;wBAC1B,IAAI,KAAK,GAAG,oBAAoB,CAAC;wBACjC,IAAI,OAAO,GAAG,CAAC,KAAK,CAAC,CAAC,IAAI,CAAC,MAAM,CAAC,WAAW,CAAC,QAAQ,EAAE,CAAC,CAAC;wBAC1D,MAAM,CAAC,CAAC,OAAO,IAAI,OAAO,CAAC,MAAM,GAAG,CAAC,CAAC,GAAG,OAAO,CAAC,CAAC,CAAC,GAAG,EAAE,CAAC;oBAC7D,CAAC,CAAC;oBAEM,WAAM,GAAG;wBACb,IAAI,OAAO,GAAG,IAAI,cAAO,EAAE,CAAC;wBAC5B,OAAO,CAAC,MAAM,CAAC,cAAc,EAAE,kBAAkB,CAAC,CAAC;wBACnD,MAAM,CAAC,IAAI,qBAAc,CAAC,EAAE,OAAO,EAAE,OAAO,EAAE,CAAC,CAAC;oBACpD,CAAC,CAAC;gBAlCF,CAAC;gBAJL;oBAAC,iBAAU,EAAE;;iCAAA;gBAyCb,oBAAC;YAAD,CAAC,AAxCD,IAwCC;YAxCD,yCAwCC,CAAA","sourcesContent":["﻿import {Injectable} from \"angular2/core\";\r\nimport {Http, Headers, RequestOptions} from \"angular2/http\";\r\nimport {Observable} from \"rxjs/Observable\";\r\nimport \"rxjs/Rx\";\r\nimport {IQuery} from \"../GeneratedFiles/IQuery\";\r\nimport {ICommand} from \"../GeneratedFiles/ICommand\";\r\nimport {CommandResponse} from \"../GeneratedFiles/CommandResponse\";\r\n\r\n@Injectable()\r\nexport class BackendCaller {\r\n\r\n    constructor(private http: Http) {\r\n    }\r\n\r\n    public test = (q: IQuery<string>): Observable<string> => {\r\n        return null;\r\n    };\r\n\r\n    public sendQuery = <TResult>(query: IQuery<TResult>): Observable<TResult> => {\r\n        var queryName = this.getName(query);\r\n        var url = `api/query/${queryName}`;\r\n        return this.httpPost<TResult>(url, query);\r\n    };\r\n\r\n    public sendCommand = (command: ICommand): Observable<CommandResponse> => {\r\n        var commandName = this.getName(command);\r\n        var url = `api/command/${commandName}`;\r\n        return this.httpPost<CommandResponse>(url, command);\r\n    };\r\n\r\n    private httpPost = <TResult>(url: string, data: any): Observable<TResult> => {\r\n        var observable = this.http.post(url, JSON.stringify(data), this.header())\r\n            .map<TResult>(response => response.json());\r\n        return observable;\r\n    };\r\n\r\n    private getName = (action: any): string => {\r\n        var regex = /function (.{1,})\\(/;\r\n        var results = (regex).exec(action.constructor.toString());\r\n        return (results && results.length > 1) ? results[1] : \"\";\r\n    };\r\n\r\n    private header = () => {\r\n        var headers = new Headers();\r\n        headers.append(\"Content-Type\", \"application/json\");\r\n        return new RequestOptions({ headers: headers });\r\n    };\r\n\r\n\r\n}"]}`

map-file without inlineSource:
`{"version":3,"file":"backendCaller.service.js","sourceRoot":"","sources":["../../../app/BackendApi/backendCaller.service.ts"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;YASA;gBAEI,uBAAoB,IAAU;oBAFlC,iBAwCC;oBAtCuB,SAAI,GAAJ,IAAI,CAAM;oBAGvB,SAAI,GAAG,UAAC,CAAiB;wBAC5B,MAAM,CAAC,IAAI,CAAC;oBAChB,CAAC,CAAC;oBAEK,cAAS,GAAG,UAAU,KAAsB;wBAC/C,IAAI,SAAS,GAAG,KAAI,CAAC,OAAO,CAAC,KAAK,CAAC,CAAC;wBACpC,IAAI,GAAG,GAAG,eAAa,SAAW,CAAC;wBACnC,MAAM,CAAC,KAAI,CAAC,QAAQ,CAAU,GAAG,EAAE,KAAK,CAAC,CAAC;oBAC9C,CAAC,CAAC;oBAEK,gBAAW,GAAG,UAAC,OAAiB;wBACnC,IAAI,WAAW,GAAG,KAAI,CAAC,OAAO,CAAC,OAAO,CAAC,CAAC;wBACxC,IAAI,GAAG,GAAG,iBAAe,WAAa,CAAC;wBACvC,MAAM,CAAC,KAAI,CAAC,QAAQ,CAAkB,GAAG,EAAE,OAAO,CAAC,CAAC;oBACxD,CAAC,CAAC;oBAEM,aAAQ,GAAG,UAAU,GAAW,EAAE,IAAS;wBAC/C,IAAI,UAAU,GAAG,KAAI,CAAC,IAAI,CAAC,IAAI,CAAC,GAAG,EAAE,IAAI,CAAC,SAAS,CAAC,IAAI,CAAC,EAAE,KAAI,CAAC,MAAM,EAAE,CAAC;6BACpE,GAAG,CAAU,UAAA,QAAQ,IAAI,OAAA,QAAQ,CAAC,IAAI,EAAE,EAAf,CAAe,CAAC,CAAC;wBAC/C,MAAM,CAAC,UAAU,CAAC;oBACtB,CAAC,CAAC;oBAEM,YAAO,GAAG,UAAC,MAAW;wBAC1B,IAAI,KAAK,GAAG,oBAAoB,CAAC;wBACjC,IAAI,OAAO,GAAG,CAAC,KAAK,CAAC,CAAC,IAAI,CAAC,MAAM,CAAC,WAAW,CAAC,QAAQ,EAAE,CAAC,CAAC;wBAC1D,MAAM,CAAC,CAAC,OAAO,IAAI,OAAO,CAAC,MAAM,GAAG,CAAC,CAAC,GAAG,OAAO,CAAC,CAAC,CAAC,GAAG,EAAE,CAAC;oBAC7D,CAAC,CAAC;oBAEM,WAAM,GAAG;wBACb,IAAI,OAAO,GAAG,IAAI,cAAO,EAAE,CAAC;wBAC5B,OAAO,CAAC,MAAM,CAAC,cAAc,EAAE,kBAAkB,CAAC,CAAC;wBACnD,MAAM,CAAC,IAAI,qBAAc,CAAC,EAAE,OAAO,EAAE,OAAO,EAAE,CAAC,CAAC;oBACpD,CAAC,CAAC;gBAlCF,CAAC;gBAJL;oBAAC,iBAAU,EAAE;;iCAAA;gBAyCb,oBAAC;YAAD,CAAC,AAxCD,IAwCC;YAxCD,yCAwCC,CAAA"}`

**Comment by Kavorka79** [comment]
I added a boolean property, useInlineSource, to the options object passed in the gulp file that prevent sourceStore to be populated and that prevents the problem even though inlineSource: true.

this way no sources are passed to Istanbul reporter and no strange folders are created. I don't know the intent of passing the sources to Istanbul so maybe you could just add this option in some form?

gulp task:
```
gulp.task("remap-to-typescript", function() {
    gulp.src("coverage/json/coverage-final.json")
        .pipe(remapIstanbul({
            reports: {
                html: "coverage/html"
            },
            useInlineSource: false
        }));
});
```

remap.js line: 321
```
/* if there are inline sources and a store to put them into, we will populate it */
var inlineSourceMap = {};
if (sourceMap.sourcesContent && options.useInlineSource) {
	sourceMap.sourcesContent.forEach(function (source, idx) {
		inlineSourceMap[sourceMap.sources[idx]] = true;
		getSourceCoverage(srcCoverage, sourceMap.sources[idx]).data.code = codeIsArray ? source.split('\n') : source;
		if (sourceStore) {
			sourceStore.set(sourceMap.sources[idx], source);
		}
	});
}
```

**Comment by dylans** [comment]
@Kavorka79 if you're still interested in this, could you please test with version 0.8.4 and let us know if you still have this issue.
