### ISSUE TITLE
WeakMap is not defined

### ISSUE THREAD

**Issue by stevehipwell** [SitePen/remap-istanbul#8]
I'm getting the following error when trying to use the gulp plugin (under Visual Studio 2015). I've upgraded to the latest node.js version and it's still an issue.

```
cmd.exe /c gulp --tasks-simple
ReferenceError: WeakMap is not defined
    at Object.<anonymous> (C:\Users\hipwells\Git\gk-online\src\app\node_modules\remap-istanbul\lib\remap.js:18:21)
    at runFactory (C:\Users\hipwells\Git\gk-online\src\app\node_modules\remap-istanbul\node_modules\amdefine\amdefine.js:183:30)
    at define (C:\Users\hipwells\Git\gk-online\src\app\node_modules\remap-istanbul\node_modules\amdefine\amdefine.js:277:13)
    at Object.<anonymous> (C:\Users\hipwells\Git\gk-online\src\app\node_modules\remap-istanbul\lib\remap.js:4:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at req (C:\Users\hipwells\Git\gk-online\src\app\node_modules\remap-istanbul\node_modules\amdefine\amdefine.js:144:31)
```

**Comment by kitsonk** [comment]
Specfically what version of NodeJS are you running?  WeakMap was available from Node 0.12 and later or any version of io.js.  I suspect whatever version gulp is finding is not the right version.

**Comment by stevehipwell** [comment]
I'm running version v4.1.2 and was previously running v0.12.7. Neither of these versions work.

**Comment by kitsonk** [comment]
Not that I am trying to blame, but I think the gulp CLI is grabbing some other version of node.  We aren't doing anything strange in how we [access WeakMap](https://github.com/SitePen/remap-istanbul/blob/09ea8db725a933306108044fde2194969210dfce/lib/remap.js#L18), it just isn't present in the global namespace.

I have looked to see if you can get gulp CLI to output the version of node it is using, but I haven't been able to find anything.

**Comment by radpet** [comment]
@stevehipwell  In you gulp task are you require-ing remap-istanbul or its gulp task?

**Comment by stevehipwell** [comment]
@kitsonk - This machine only has a single version of node present and it is reporting the correct version.

@radpet - I'm requiring the gulp task as documented in the wiki.

**Comment by kitsonk** [comment]
@stevehipwell I don't know what to say... WeakMap is defined in the global namespace but isn't present in the version of node the code above is being executed in.

**Comment by kinday** [comment]
@stevehipwell, looks like Visual Studio uses some bundled Node.js version and it may require `--harmony` flag to use WeakMap or even not support it at all. Try to [synchronize it](http://ryanhayes.net/synchronize-node-js-install-version-with-visual-studio-2015/) to your external Node.js instllation.

**Comment by stevehipwell** [comment]
@kinday I've set Visual Studio to use my system node.

**Comment by kinday** [comment]
@stevehipwell, let’s make sure it’s the one used by gulp.

Add this line at the beginning of your `gulpfile.js`, please:
```js
console.log('Node.js version:', process.version);
```

**Comment by stevehipwell** [comment]
@kinday I'm getting v4.1.6 returned.

**Comment by kitsonk** [comment]
*sigh* this is getting silly isn't it? :frowning: How about the following added to `gulpfile.js`:

```javascript
console.log('typeof WeakMap:', typeof WeakMap);
```

**Comment by stevehipwell** [comment]
@kitsonk the following is what is printed on my console.

```
Node.js version: v4.1.2
typeof WeakMap: function
```

**Comment by stevehipwell** [comment]
And just like that it looks like it's working, I have no idea what's changed.

Thanks for your help.

**Comment by kitsonk** [comment]
Ok, very very very silly... when it gets to `remap.js` it is then undefined... :cry:  If you are up for it, it is time to hack the code and see what is going on.  Can you put those two lines into `gk-online\src\app\node_modules\remap-istanbul\lib\remap.js` before line 18?

**Comment by stevehipwell** [comment]
It returns the following.

```
Node.js version: v4.1.2
typeof WeakMap: function
```

I think this was machine specific and I've no idea what I changed on my machine before trying those commands.

**Comment by kinday** [comment]
@kitsonk, yep, silly. But it is kinda _resolved_ now. And we can be almost sure it is nothing about `remap-istanbul` itself.

**Comment by kitsonk** [comment]
Ok, closing for now... if it reoccurs let us know.
