### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by Cayan** [SitePen/remap-istanbul#86]
As I've read a lot of different topics regarding this issue, it seems to be an old bug.

Using JSON output generated by karma-coverage v1.1.1

These are my test results for different versions:
Versions >= 0.6.2

0.6.0 and 0.6.1:
- HTML reports the same folder twice (the second time with absolute paths and 100% coverage).

0.5.1: working fine.

**Comment by dylans** [comment]
@Cayan is this an issue with remap-istanbul or karma-remap-istanbul. Also have you tested this with 0.8.4?

**Comment by Cayan** [comment]
I haven't worked with this in a while.
I'll probably have to reimplement this on a new CI (later this week, probably).

Once I do that, I'll give you a feedback

**Comment by martinoppitz** [comment]
istanbul/issues/5#issuecomment-273530488

**Comment by martinoppitz** [comment]
https://github.com/marcules/karma-remap-istanbul/issues/5
