### ISSUE TITLE
Update istanbul to latest version

### ISSUE THREAD

**Issue by Hirse** [SitePen/remap-istanbul#88]
The currently required version of istanbul (0.4.3) transitively depends on a vulnerable version of minimatch (2.0.x by using fileset@0.2.1) which logs a warning in npm:
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

Updating the istanbul dependency to the latest version ([0.4.5](https://github.com/gotwarlost/istanbul/releases/tag/v0.4.5)) would solve this issue as the fileset dependency has been removed from istanbul.

**Comment by dylans** [comment]
Closed via fc6daf2
