### ISSUE TITLE
Hardcoded path

### ISSUE THREAD

**Issue by radpet** [SitePen/remap-istanbul#9]
Hello, I have noticed that even if I change the basePath property remap-istanbul still adds 'source/' between the basePath and the files. Any ideas how can I disable/configure it?

**Comment by kitsonk** [comment]
It isn't "hardcoded".  What is occurring is that source maps contain a location for the source files.  `basePath` is intended to be used when you have moved your source files from the location they were when the source maps were generated, but the source maps can still contain relative filenames, which are what are being parsed out.

Right now, there is not currently mechanism to wholesale substitute file paths, though if the source map is relative, a `basePath` that resolves the relevance can be used, but what finally gets emitted in the output is relative to where `remap-istanbul` is run.

Can you provide a bit of your project structure?  Where are your emitted files located, where are your source maps located, what is the path in the source maps and where are the original source files located at the time you run `remap-istanbul`?

**Comment by radpet** [comment]
@kitsonk Hello, I am having es6 code in 'src' folder which is transpiled with babel and it is located in 'build'. Then with the help of istanbul I create new 'build-istanbul' which has its source wrapped in the istanbul methods. Then i create reports and based on those reports I use remap-istanbul to map the build code to its original source. However, when i open the remapped json's I see that the path has this 'source/' inside. Despite the fact that the source-map path is relative I am able to with the use of the basePath property to locate the source folder - 'src'. I had quick look on 'remap-istanbul' code but couldn't find why this 'source/' is used :+1: .

**Comment by kitsonk** [comment]
@radpet it isn't, which is why I suspect it is either coming from the source maps or the coverage, or relative to where you are running `remap-istanbul` from.  There is no hard coding of paths at all.

**Comment by kitsonk** [comment]
Can you try release 0.3.1?  I think the PR in #10 might address your issue.

**Comment by kitsonk** [comment]
Closing due to no response.
