### ISSUE TITLE
Next release ?

### ISSUE THREAD

**Issue by sirrocco** [SitePen/remap-istanbul#97]
Hi,

There's a commit since the last release that would add an important fix for all people using node 6. Do you have an estimate of when the next release might happen?

Thank you.

**Comment by sebastianovide** [comment]
created an Issue about node 7: https://github.com/SitePen/remap-istanbul/issues/103

**Comment by dylans** [comment]
Release was made recently, https://github.com/SitePen/remap-istanbul/releases/tag/0.8.0
